### GET /invoices
GET http://localhost:1234/invoices
Accept: application/json

### GET Invoices by date
GET http://localhost:1234/invoices?from=2024-08-08&to=2024-08-10
Accept: application/json

### Add invoice
POST http://localhost:1234/invoices
Content-Type: application/json

{
    "date": "2020-12-01",
    "entity_id": 1,
    "total": 1000
}

### Get Pending Invoices from suppliers
GET http://localhost:1234/invoices/pending-suppliers
Accept: application/json