### Get payments
GET http://localhost:1234/payments
Accept: application/json

### GET payments by invpuce id
GET http://localhost:1234/payments?invoice_id=1
Accept: application/json

### Add payment
POST http://localhost:1238/payments
Content-Type: application/json

{
    "invoice_id": 1,
    "date": "2024-08-02",
    "amount": "asd",
    "payment_method": "cash",
    "type": "expense"
}

