### Get payments
GET http://localhost:1234/payments
Accept: application/json

## GET payments by date
GET http://localhost:1234/invoices?date=2024-07-16
Accept: application/json

### Add invoice
POST http://localhost:1234/invoices
Content-Type: application/json

{
    "date": "2020-01-01",
    "client": "John Doe",
    "amount": 1000
}

