### GET /users
GET http://localhost:1234/users
Accept: application/json
    
### GET /roles
GET http://localhost:1234/users/roles
Accept: application/json
    

### GET /users/:id
GET http://localhost:1234/users/fd50e252-4eee-4b4b-92a1-2b21aa724184
Accept: application/json

### refreshAccessToken
GET http://localhost:1234/users/refresh-token

### validate accessToken
GET http://localhost:1234/users/me


### Login
POST http://localhost:1234/users/login
Content-Type: application/json

{
    "username": "gus",
    "password": "123456"
}

### Register
POST http://localhost:1234/users/register
Content-Type: application/json

{
    "username": "gusta9",
    "password": "123456",
    "roleId": 4
}

### LogoutallAsync
POST http://localhost:1234/users/logout

### Delete User
DELETE http://localhost:1234/users/061b56b0-2bb3-4660-a932-dd6f0b0a22f0